version: "3.9"

services:
  mysqlDb:
    image: mysql:5.7
    container_name: mysqlDb
    environment:
      MYSQL_DATABASE: api
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend
    ports:
      - "3306:3306"
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysqlDb
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlDb:3306/api?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_NAME: api
    ports:
      - "1000:1000"

networks:
  backend:
    driver: bridge