version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/api?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_PASSWORD:
      SPRING_DATASOURCE_USER: root
      SPRING_DATASOURCE_NAME: api
    ports:
      - "1000:1000"


